---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels: {}
  name: postgresinstances.kompost.io
spec:
  group: kompost.io
  names:
    kind: PostgresInstance
    plural: postgresinstances
    shortNames:
      - pginst
    singular: postgresinstance
  scope: Namespaced
  versions:
    - additionalPrinterColumns: []
      deprecated: false
      deprecationWarning:
      name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              anyOf:
                - required:
                    - hostname
                    - port
                    - username
                    - passwordSecretRef
                - required:
                    - hostname
                    - port
                    - username
                    - plainPassword
              properties:
                hostname:
                  type: string
                passwordSecretRef:
                  properties:
                    key:
                      type: string
                    name:
                      type: string
                  required:
                    - name
                    - key
                  type: object
                plainPassword:
                  description: It's not safe to save passwords in plaintext. Consider using argsFrom instead.
                  type: string
                port:
                  type: integer
                username:
                  type: string
              type: object
            status:
              properties:
                conditions:
                  items:
                    properties:
                      lastTransitionTime:
                        format: date-time
                        type: string
                      message:
                        type: string
                      status:
                        type: string
                        enum: [True, False]

                      type:
                        type: string
                    type: object
                  type: array
                observedGeneration:
                  type: integer
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: {}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: kompost
  name: kompost
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - "*"
  - apiGroups:
      - kompost.io
    resources:
      - postgresinstances
    verbs:
      - "*"
  - apiGroups:
      - kompost.io
    resources:
      - postgresinstances/status
    verbs:
      - "*"
  - apiGroups:
      - v1
    resources:
      - Secret
    verbs:
      - get
      - list

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: kompost
  name: kompost
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: kompost
  name: kompost
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kompost
subjects:
  - kind: ServiceAccount
    name: kompost
    namespace: default
