---
apiVersion: v1
kind: Namespace
metadata:
  name: temporal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  temporal
  namespace: temporal
  labels:
    app:  temporal
spec:
  selector:
    matchLabels:
      app: temporal
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  temporal
    spec:
      containers:
        - name: temporal
          image: temporalio/auto-setup
          imagePullPolicy: IfNotPresent
          # args: ['-c', 'max_connections=100']
          ports:
            - name: main
              containerPort: 7233
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 32Mi
          env:
            - name: DB
              value: postgresql
            - name: POSTGRES_SEEDS
              value: postgres.postgres.svc.cluster.local
            - name: TEMPORAL_ADDRESS
              value: 127.0.0.1:7223
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: config/dynamicconfig/development-sql.yaml
              # DB_PORT filled by mix kompost.gen.periphery
              # POSTGRES_USER filled by mix kompost.gen.periphery
              # POSTGRES_PWD filled by mix kompost.gen.periphery
          volumeMounts:
            - name: dynamicconfig
              mountPath: /etc/temporal/config/dynamicconfig
      volumes:
        - name: dynamicconfig
          configMap:
            name: dynamicconfig

# configmap: creted by mix kompost.gen.periphery
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: temporal
spec:
  selector:
    app: temporal
  type: NodePort
  ports:
  - name: temporal
    protocol: TCP
    targetPort: main
    # nodePort and port: filled by mix kompost.gen.periphery