---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: kompost
  name: kompost
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - get
      - list
      - update
      - patch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - '*'
  - apiGroups:
      - kompost.chuge.li
    resources:
      - postgresclusterinstances
    verbs:
      - '*'
  - apiGroups:
      - kompost.chuge.li
    resources:
      - postgresclusterinstances/status
    verbs:
      - '*'
  - apiGroups:
      - kompost.chuge.li
    resources:
      - postgresdatabases
    verbs:
      - '*'
  - apiGroups:
      - kompost.chuge.li
    resources:
      - postgresdatabases/status
    verbs:
      - '*'
  - apiGroups:
      - kompost.chuge.li
    resources:
      - postgresinstances
    verbs:
      - '*'
  - apiGroups:
      - kompost.chuge.li
    resources:
      - postgresinstances/status
    verbs:
      - '*'
  - apiGroups:
      - kompost.chuge.li
    resources:
      - temporalapiservers
    verbs:
      - '*'
  - apiGroups:
      - kompost.chuge.li
    resources:
      - temporalapiservers/status
    verbs:
      - '*'
  - apiGroups:
      - kompost.chuge.li
    resources:
      - temporalnamespaces
    verbs:
      - '*'
  - apiGroups:
      - kompost.chuge.li
    resources:
      - temporalnamespaces/status
    verbs:
      - '*'
