---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: kompost
  name: kompost
  namespace: kompost
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kompost
  template:
    metadata:
      labels:
        k8s-app: kompost
    spec:
      containers:
        - env:
            - name: MIX_ENV
              value: prod
            - name: BONNY_OPERATOR_NAME
              value: kompost
            - name: BONNY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BONNY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BONNY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: BONNY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          image: kompost:e2e
          name: kompost
          ports:
            - containerPort: 4000
              name: webhooks
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
          volumeMounts:
            - mountPath: /mnt/cert
              name: certs
      initContainers:
        - args:
            - eval
            - Kompost.Webhooks.bootstrap_tls(:prod, "tls-certs")
          image: kompost:e2e
          name: init-certificates
      serviceAccountName: kompost
      volumes:
        - name: certs
          secret:
            optional: true
            secretName: tls-certs
