---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kompost
  name: kompost
  namespace: kompost
spec:
  ports:
    - name: webhooks
      port: 443
      protocol: TCP
      targetPort: webhooks
  selector:
    k8s-app: kompost
