apiVersion: v2
name: kompost
description: A Helm chart for Kompost

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.3.1"

annotations:
  artifacthub.io/category: database
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/changes: |
    - kind: added
      description: Postgres Kompo - Database Naming Strategy
      links:
        - name: GitHub PR
          url: https://github.com/mruoss/kompost/pull/38
        - name: GitHub PR
          url: https://github.com/mruoss/kompost/pull/42
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: |
    - name: Michael Ruoss
      email: michael@michaelruoss.ch
  artifacthub.io/operator: "true"
  artifacthub.io/prerelease: "true"
  artifacthub.io/links: |
    - name: GitHub
      url: https://github.com/mruoss/kompost
    - name: Documentation
      url: https://kompost.chuge.li
  artifacthub.io/signKey: |
    fingerprint: 4B95C7BE876C3E22ED79A56F15B49C3F51E14030
    url: https://github.com/mruoss/kompost/raw/main/priv/charts/pubkey.asc    
  artifacthub.io/images: |
    - name: kompost
      image: ghcr.io/mruoss/kompost:latest
      whitelisted: true
      platforms:
        - linux/amd64
        - linux/arm/v7
        - linux/arm64
    - name: kompost-slim
      image: ghcr.io/mruoss/kompost:latest-slim
      whitelisted: true
      platforms:
        - linux/amd64
        - linux/arm/v7
        - linux/arm64
    - name: kompost-alpine
      image: ghcr.io/mruoss/kompost:latest-alpine
      platforms:
        - linux/amd64
        - linux/arm/v7
        - linux/arm64
