{{- if .Values.kompos.postgres.enabled }}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: postgresinstances.kompost.chuge.li
spec:
  group: kompost.chuge.li
  names:
    kind: PostgresInstance
    plural: postgresinstances
    shortNames:
      - pginst
    singular: postgresinstance
  scope: Namespaced
  versions:
    - deprecationWarning:
      name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              anyOf:
                - required:
                    - hostname
                    - port
                    - username
                    - passwordSecretRef
                - required:
                    - hostname
                    - port
                    - username
                    - plainPassword
              properties:
                hostname:
                  type: string
                passwordSecretRef:
                  properties:
                    key:
                      type: string
                    name:
                      type: string
                  required:
                    - name
                    - key
                  type: object
                plainPassword:
                  description: It's not safe to save passwords in plaintext. Consider using passwordSecretRef instead.
                  type: string
                port:
                  type: integer
                ssl:
                  properties:
                    ca:
                      description: CA certificates used to validate the server cert against.
                      type: string
                    enabled:
                      description: Set to true if ssl should be used.
                      type: boolean
                    verify:
                      description: "'verify_none' or 'verify_peer'. Defaults to 'verify_none'"
                      type: string
                  type: object
                username:
                  type: string
              type: object
            status:
              properties:
                conditions:
                  items:
                    properties:
                      lastHeartbeatTime:
                        format: date-time
                        type: string
                      lastTransitionTime:
                        format: date-time
                        type: string
                      message:
                        type: string
                      status:
                        enum:
                          - 'True'
                          - 'False'
                        type: string
                      type:
                        type: string
                    type: object
                  type: array
                observedGeneration:
                  type: integer
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: {}
{{- end }}