{{- if .Values.kompos.temporal.enabled }}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: temporalapiservers.kompost.chuge.li
spec:
  group: kompost.chuge.li
  names:
    kind: TemporalApiServer
    plural: temporalapiservers
    shortNames:
      - tmprlas
    singular: temporalapiserver
  scope: Namespaced
  versions:
    - deprecationWarning:
      name: v1alpha1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              anyOf:
                - required:
                    - host
                    - port
                - required:
                    - host
                    - port
              properties:
                host:
                  type: string
                port:
                  type: integer
              type: object
            status:
              properties:
                conditions:
                  items:
                    properties:
                      lastHeartbeatTime:
                        format: date-time
                        type: string
                      lastTransitionTime:
                        format: date-time
                        type: string
                      message:
                        type: string
                      status:
                        enum:
                          - 'True'
                          - 'False'
                        type: string
                      type:
                        type: string
                    type: object
                  type: array
                observedGeneration:
                  type: integer
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
      subresources:
        status: {}
{{- end }}