---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kompost.fullname" . }}
  labels:
    {{- include "kompost.labels" . | nindent 4 }}
  {{- if and .Values.webhook.certManager.enabled .Values.webhook.certManager.addInjectorAnnotations }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kompost.fullname" . }}-webhook
  {{- end }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "kompost.fullname" . }}-webhook
        namespace: {{ .Release.Namespace | quote }}
        path: /postgres/admission-review/validating
        port: 443
    failurePolicy: Ignore
    matchPolicy: Equivalent
    name: postgres.kompost.chuge.li
    rules:
      - apiGroups:
          - kompost.chuge.li
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - postgresdatabases
          - postgresclusterinstances
          - postgresinstances
    sideEffects: None
