---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kompost.fullname" . }}-webhook
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kompost.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: http
  selector:
    {{- include "kompost.selectorLabels" . | nindent 4 }}
