{{- if .Values.webhook.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kompost.fullname" . }}-webhook
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "kompost.labels" . | nindent 4 }}
  {{- with .Values.webhook.certManager.cert.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  commonName: {{ include "kompost.fullname" . }}-webhook
  dnsNames:
    - {{ include "kompost.fullname" . }}-webhook
    - {{ include "kompost.fullname" . }}-webhook.{{ .Release.Namespace }}
    - {{ include "kompost.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
  issuerRef:
    {{- toYaml .Values.webhook.certManager.cert.issuerRef | nindent 4 }}
  {{- with .Values.webhook.certManager.cert.duration }}
  duration: {{ . | quote }}
  {{- end }}
  {{- with .Values.webhook.certManager.cert.renewBefore }}
  renewBefore: {{ . | quote }}
  {{- end }}
  secretName: {{ include "kompost.fullname" . }}-webhook-tls
{{- end }}