name: Build and Publish
on:
  workflow_dispatch:
  push:
    tags: [v*]
    branches: [main]

permissions:
  contents: write

env:
  MIX_ENV: prod
  KUBECONFIG: /home/runner/.kube/config
  ELIXIR_IMAGE: elixir:1.14.3-otp-24
  ERLANG_IMAGE: erlang:24.3.4.7

jobs:
  build_container_image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["", -slim, -alpine]
    permissions:
      packages: write
      contents: write
    outputs:
      docker_image: ${{ steps.prepare_vars.outputs.docker_image }}
    steps:
      - uses: actions/checkout@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Prepare variables
        id: prepare_vars
        run: |
          if [[ "${{ github.ref_name }}" == "tag" ]]; then
            TAG=dev
          else
            TAG=${{ github.ref_name }}
          fi

          echo "docker_image=ghcr.io/mruoss/kompost:${TAG#v}${{ matrix.arch }}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.prepare_vars.outputs.docker_image }}
          platforms: linux/amd64,linux/arm64/v8,linux/arm
          cache-from: type=registry,ref=ghcr.io/mruoss/kompost:dev
          cache-to: type=inline
          build-args: |
            ERLANG_IMAGE=${{ env.ERLANG_IMAGE }}${{ matrix.arch }}
            ELIXIR_IMAGE=${{ env.ELIXIR_IMAGE }}${{ matrix.arch }}

      - uses: cloudposse/github-action-matrix-outputs-write@main
        id: out
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: arch${{ matrix.arch }}
          outputs: |-
            docker_image: ${{ steps.prepare_vars.outputs.docker_image }}

  create_gh_release:
    runs-on: ubuntu-latest
    needs: [build_container_image]
    if: github.ref_type == 'tag'
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v3

      - name: Prepare release notes
        run: |
          csplit -s CHANGELOG.md "/^## /" {1}
          cat xx01 > release_nots.md

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          body_path: release_nots.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
  
  read_matrix_output:
    runs-on: ubuntu-latest
    needs: [build_container_image]
    if: github.ref_type == 'tag'
    steps:
      - uses: cloudposse/github-action-matrix-outputs-read@main
        id: read
        with:
          matrix-step-name: build_container_image

    outputs:
      docker_image: "${{ steps.read.outputs.docker_image }}"

  upload_manifests:
    runs-on: ubuntu-latest
    needs: [read_matrix_output, create_gh_release]
    steps:
      - uses: actions/checkout@v3

      - name: Setup elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.14.x
          otp-version: 25.x

      - name: Install Mix Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: build manifest
        run: |
          mix bonny.gen.manifest --image "${{ needs.read_matrix_output.outputs.docker_image }}" --namespace kompost -o manifest${{ matrix.arch }}.yaml

      - name: upload manifest as artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_gh_release.outputs.upload_url }}
          asset_path: ./manifest${{ matrix.arch }}.yaml
          asset_name: manifest${{ matrix.arch }}.yaml
          asset_content_type: application/yaml