name: Build and Publish
on:
  workflow_run:
    workflows: ["Run Tests"]
  push:
    tags: [v*]

env:
  MIX_ENV: prod
  KUBECONFIG: /home/runner/.kube/config

jobs:
  build_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.14.x]
        otp: [25.x]
        arch: [alpine]
    steps:
      - uses: actions/checkout@v3

      - name: Setup elixir
        id: beam
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}

      - name: Build Release
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.clean --unused
          mix compile --warnings-as-errors
          mix release --overwrite --quiet

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Vars
        run: |
          TAG=${{ github.ref_name }}
          OTP_VERSION=${{ steps.beam.outputs.otp-version }}

          echo "DOCKER_TAG_VERSION=${TAG#v}" >> $GITHUB_ENV
          echo "ERLANG_DOCKER_IMAGE_VERSION=${OTP_VERSION#OTP-}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./dockerbuild
          tags: mruoss/kompost:${{ env.DOCKER_TAG_VERSION }}-${{ matrix.arch }}
          build-args: |
            ERLANG_IMAGE_TAG=${{ env.ERLANG_DOCKER_IMAGE_VERSION }}-${{ matrix.arch }}
