name: Publish Helm Chart
on:
  workflow_dispatch:

env:
  MIX_ENV: prod
  KUBECONFIG: /home/runner/.kube/config

permissions:
  contents: read
  packages: write
  
jobs:
  publish_chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push Helm chart to GitHub Registry
        uses: bsord/helm-push@v4
        with:
          useOCIRegistry: true
          registry-url:  oci://ghcr.io/${{ github.repository }}
          username: mruoss
          access-token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          chart-folder: priv/chart
